name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SirFaizdat
website: ${project.url}
main: io.github.sirfaizdat.prison.Prison
commands:
  prison:
    description: Commands for managing and checking on Prison.
    usage: /prison <subcommand> [args...]